### PR TITLE
example data added

### PR DESCRIPTION
**Pull request by sawsimeon**
Louai, 

I added several pdbqt file for the data. Can you make a tutorial on how to use the .ccp file because I do not know how to use it. Thanks a bunch.

### CODE REVIEW

**Comment by LouaiKB** [comment]
I will add the Makefiles later

**Comment by sawsimeon** [comment]
Cool. Thanks

**Comment by sawsimeon** [comment]
Before I forgot, can you also add the file to unzip sub-tranche and tranche folder. Thanks.  @LouaiKB 😃

**Comment by LouaiKB** [comment]
@sawsimeon I pushed the bash code for that :)

**Comment by sawsimeon** [comment]
got it, thanks!

**Pull request merged**
